-- INSERTAR

-- SELECCIONAR BASE DE DATOS
USE `voto-vision`;

-- CODIFICACIÓN
SET NAMES utf8mb4;

-- SELECCIONAR TABLA
SELECT * FROM `APLICACION_MODELO` ORDER BY `CAMPO_1` asc;

-- REINICIAR INCREMENTO
ALTER TABLE `APLICACION_MODELO` AUTO_INCREMENT = 1;

-- INSERTAR DATOS
INSERT INTO `APLICACION_MODELO` (`id`,`CAMPO_1`,`CAMPO_2`,`CAMPO_3`,`CAMPO_4`,`CAMPO_5`) 
VALUES 
(1,'VALOR_CAMPO_1','VALOR_CAMPO_2','VALOR_CAMPO_3','VALOR_CAMPO_4','VALOR_CAMPO_5'),
(2,'VALOR_CAMPO_1','VALOR_CAMPO_2','VALOR_CAMPO_3','VALOR_CAMPO_4','VALOR_CAMPO_5');